### ISSUE TITLE
user: openground page

### ISSUE THREAD

**Issue by dhruvilp** [dhruvilp/cs419-ml-group1#16]
# Task Description:
### Implement UI based on the `app_design` doc

**Comment by dhruvilp** [comment]
@jujg99 for search bar you can use these, it's little simpler and easy to implement
![Screen Shot 2020-04-27 at 3 32 15 PM](https://user-images.githubusercontent.com/38077836/80412941-9daf2b80-889c-11ea-83c4-9c4482f361e7.png)

### Note: we'll allow users to select only 1 model and upload 1 image to attack

**Comment by jujg99** [comment]
@dhruvilp I just want to make sure I have the right idea of what the page is doing. So the drop down bar (search bar) is for selecting one of the existing models, so it should be initially filled with 1. MNIST (model tf-68) and 2. CIFAR-10 (model tf-45). And the drag and drop or upload file box is for the user to upload an attack image? And then what is the bottom upload button for?

**Comment by dhruvilp** [comment]
@jujg99 
1. yes, Search bar allows users to select 1 existing model
2. yes, we can have models uploaded by admin for 1 & 2
3. ignore `upload` button part, i updated design doc. (drag&drop allows to upload an image and then submit attack)
